#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <array>

using namespace std;

struct instuction{
    string_view hex;
    string_view mnemonic;
    void (*action)();
};

void err(){ cout << "FE(Invalid code)" << endl; }
void ext(){ cout << "(Exited with code 255[Executed code])" << endl; exit(255); }

static constexpr array<instuction, 2> instuctions{{ // Table used for adding more instructions in the future. Feel free to modyfy this table, but remember that your emulated code can break.
    
    {"FE", "err", &err},
    {"FF", "ext", &ext},

}};

string Terminal;

void TerminalF(){ // Main terminal. DO NO MODIFY THIS FUNCTION
    while (true){
        cin >> Terminal;
        transform(Terminal.begin(), Terminal.end(), Terminal.begin(), ::toupper);
        if (Terminal.length() == 2){
            bool found = false;
            for(const auto& inst : instuctions){
                if (Terminal == inst.hex){
                    inst.action();
                    break;
                }
            }
            if (!found){
                err();
            }
        }
        else {cout << "(Invalid syntax)" << endl;}
    }
} 

int main(){
    cout << "(Mesages like this are generated by the emulator.)" << endl;
    TerminalF();
    return 0;  
}
